#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'bsm'

lines = []

ARGF.each_line do |line|
  lines << line
end

content = lines.join(' ')
gen = Bsm::Generator.new

print gen.generate(content)
